application: practical-well-728
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /admin
  static_dir: admin

# This handler routes requests to your APIs to your Endpoints code.
# See https://developers.google.com/appengine/docs/python/endpoints/
- url: /_ah/spi/.*
  script: backend.cdh_api.APPLICATION

libraries:
- name: endpoints
  version: 1.0
